window.STORY_DATA = window.STORY_DATA || { plans: [], stories: [] };
window.STORY_DATA.stories = window.STORY_DATA.stories || [];
window.STORY_DATA.stories.push({
    "id":  "toi-tro-ve-30-ngay-truoc-khi-thanh-pho-chim",
    "title":  "Tôi Trở Về 30 Ngày Trước Khi Thành Phố Chìm",
    "author":  "ThanhMV",
    "status":  "Đang ra",
    "genre":  [
                  "Mạt thế đô thị",
                  "Trọng sinh",
                  "Thiên tai",
                  "Sinh tồn",
                  "Nữ cường"
              ],
    "cover":  "assets/toi-tro-ve-30-ngay-thumb.png",
    "summary":  "Lâm An chết trong căn hộ tầng mười bảy sau khi bị hàng xóm phá cửa cướp hết nước, thuốc và lương thực trong trận đại ngập. Mở mắt ra, cô trở về đúng ba mươi ngày trước thảm họa, âm thầm tích trữ và học cách sống sót giữa một thành phố sắp chìm.",
    "updatedAt":  "2026-07-03",
    "reads":  0,
    "rating":  5,
    "chapters":  [
                     {
                         "id":  "c001",
                         "title":  "Chương 1: Tiếng Gõ Cửa Cuối Cùng",
                         "episodeTitle":  "Tập 01: Ba Mươi Ngày Trước Đại Ngập",
                         "free":  true,
                         "price":  0,
                         "body":  [
                                      "Nước bẩn đã lên tới mép giường.",
                                      "Lâm An ngồi co trong góc phòng ngủ, lưng dựa vào tủ quần áo đã mốc đen một mảng lớn. Căn hộ tầng mười bảy từng là nơi cô nghĩ có thể tránh được trận ngập. Bây giờ nó chỉ còn là một cái hộp kín, nóng, hôi, và đầy tiếng người đói ngoài hành lang.",
                                      "Cổ họng cô khô đến mức nuốt nước bọt cũng đau.",
                                      "Trên bàn còn nửa chai nước suối, loại năm trăm mililit, nắp chai đã bị cô vặn mở rồi đóng lại không biết bao nhiêu lần. Cô không dám uống hết. Người ta có thể nhịn ăn mấy ngày, nhưng thiếu nước sạch thì đầu óc bắt đầu sinh ra tiếng nói kỳ lạ.",
                                      "Tiếng nói ấy bảo cô mở cửa.",
                                      "Tiếng nói ấy bảo cô đưa nước ra ngoài, biết đâu người ta sẽ tha.",
                                      "Nhưng Lâm An đã nhìn thấy \"người ta\" tha ai bao giờ đâu.",
                                      "Ngoài cửa lại vang lên tiếng đập.",
                                      "Cộc.",
                                      "Cộc.",
                                      "Cộc.",
                                      "Không phải tiếng gõ xin giúp đỡ. Là tiếng kim loại nện vào ổ khóa.",
                                      "\"Lâm An.\" Giọng bà Hạnh tầng mười vang lên ngoài hành lang, vẫn mềm như lúc họp cư dân. \"Con mở cửa đi. Mọi người chỉ muốn nói chuyện.\"",
                                      "Lâm An nhìn bàn tay mình.",
                                      "Các đầu ngón tay cô tím bầm vì lạnh và mất máu. Ba ngày trước, cô đã dùng chính đôi tay này kéo một đứa trẻ từ cầu thang thoát hiểm lên. Đứa trẻ sốt cao. Mẹ nó quỳ xuống trước cửa nhà cô khóc đến khàn giọng.",
                                      "Cô mở cửa.",
                                      "Cô cho họ hai gói oresol, một vỉ hạ sốt, một bình nước hai lít.",
                                      "Đến tối, cả tầng đều biết nhà cô có thuốc.",
                                      "Ngày hôm sau, người ta đến xin.",
                                      "Ngày thứ ba, người ta đến đòi.",
                                      "Bây giờ, người ta đến cướp.",
                                      "\"Cô An ơi.\" Một giọng nam trẻ chen vào, là Minh, con trai bà Hạnh. \"Tụi tôi biết trong nhà cô còn đồ ăn. Cô giữ một mình cũng đâu sống được lâu. Cô chia ra, mọi người còn nhớ ơn cô.\"",
                                      "Lâm An bật cười, nhưng cổ họng khô quá, tiếng cười chỉ thoát ra như tiếng giấy ráp.",
                                      "Nhớ ơn?",
                                      "Kiếp trước cô tin hai chữ này.",
                                      "Tin đến mức để cửa mở hé.",
                                      "Tin đến mức đưa danh sách thuốc cho tổ dân phố tạm thời.",
                                      "Tin đến mức nói thật rằng trong nhà còn ba thùng nước, hai bao gạo, một ít đồ hộp và thuốc sát khuẩn.",
                                      "Một tuần sau, họ lập \"đội phân phối\". Hai tuần sau, họ nói tài nguyên phải do tập thể quản lý. Ba tuần sau, khi cô bị sốt, không ai đưa lại cho cô dù chỉ một viên hạ sốt của chính cô.",
                                      "Tập thể có rất nhiều miệng.",
                                      "Nhưng không có trí nhớ.",
                                      "Ổ khóa kêu lên một tiếng rắc.",
                                      "Lâm An chống tay đứng dậy. Đầu gối cô mềm nhũn, bụng trống rỗng co rút từng cơn. Cô cầm con dao gọt trái cây trên bàn. Lưỡi dao ngắn, cán nhựa nứt, thứ này không cứu được ai.",
                                      "Nhưng tay không thì chết càng khó coi hơn.",
                                      "Ngoài hành lang có người thì thầm:",
                                      "\"Đập nhanh lên. Nhà nó còn nước.\"",
                                      "\"Con nhỏ này ích kỷ từ đầu rồi.\"",
                                      "\"Đúng đó. Lúc trước nó đặt giao hàng cả chục chuyến, tưởng không ai thấy à?\"",
                                      "Lâm An siết cán dao.",
                                      "Thì ra họ đều thấy.",
                                      "Ngày cô vác từng thùng nước vào nhà, họ thấy.",
                                      "Ngày cô mua thêm khóa phụ, họ thấy.",
                                      "Ngày cô từ chối cho người lạ vào sạc điện thoại, họ cũng thấy.",
                                      "Chỉ là khi còn điện, còn mạng, còn shipper chạy dưới mưa, không ai nói cô ích kỷ. Họ chỉ cười, hỏi cô có phải sợ tận thế không.",
                                      "Lâm An nhớ lúc đó mình đã cười theo.",
                                      "Nếu khi ấy cô biết trước sẽ có ngày này, cô đã không cười.",
                                      "Cánh cửa bật tung.",
                                      "Gió hành lang tràn vào cùng mùi nước cống, mùi mồ hôi lâu ngày, mùi người đói. Ba bóng người đứng chắn ở cửa. Phía sau họ còn nhiều gương mặt khác, xanh xao, lấm lem, mắt sáng lên khi nhìn thấy nửa chai nước trên bàn.",
                                      "Minh là người bước vào đầu tiên.",
                                      "Trong tay hắn cầm một cây xà beng.",
                                      "\"Cô An.\" Hắn vẫn gọi cô bằng giọng tử tế. \"Đừng làm khó nhau.\"",
                                      "Lâm An lùi một bước.",
                                      "\"Nước là của tôi.\"",
                                      "Bà Hạnh đứng sau lưng con trai, thở dài rất nhẹ.",
                                      "\"Thời này rồi còn của tôi của cô gì nữa con. Cả tòa nhà phải sống chung.\"",
                                      "\"Lúc tôi sốt, thuốc của tôi ở đâu?\"",
                                      "Không ai trả lời.",
                                      "Chỉ có ánh mắt họ lảng đi trong một khoảnh khắc rất ngắn. Ngắn đến mức nếu là Lâm An của ngày xưa, cô sẽ tự lừa mình rằng họ cũng khó xử.",
                                      "Nhưng người sắp chết thường nhìn rõ hơn người đang sống.",
                                      "Minh đưa tay giật lấy chai nước.",
                                      "Lâm An lao tới.",
                                      "Cô không nghĩ mình còn sức. Nhưng khi ngón tay Minh chạm vào chai nước cuối cùng, trong ngực cô bỗng bùng lên một thứ nóng rát hơn cả đói khát. Cô đâm dao về phía trước.",
                                      "Lưỡi dao cắm vào cánh tay Minh.",
                                      "Hắn hét lên.",
                                      "Ngay sau đó, xà beng quật ngang vào vai cô.",
                                      "Cơn đau trắng xóa nổ tung trước mắt. Lâm An ngã xuống nền nhà ngập nước. Tai cô ù đi, chỉ còn nghe tiếng chân người giẫm lên nước, tiếng đồ đạc bị lục tung, tiếng ai đó reo lên khi tìm được gói mì cuối cùng trong thùng nhựa dưới gầm giường.",
                                      "\"Có đồ hộp!\"",
                                      "\"Đây còn thuốc!\"",
                                      "\"Nước, lấy nước trước!\"",
                                      "Một bàn chân đá vào bụng cô.",
                                      "Lâm An cuộn người lại. Cô nhìn thấy nửa chai nước bị giành qua giành lại, rồi đổ ra nền nhà.",
                                      "Nước sạch chảy thành một đường mỏng, hòa vào nước bẩn dưới sàn.",
                                      "Không ai cúi xuống hứng.",
                                      "Không ai tiếc.",
                                      "Chỉ có Lâm An nhìn nó đến đỏ mắt.",
                                      "Cả đời cô chưa từng hận ai như vậy.",
                                      "Hận bà Hạnh với cái miệng lúc nào cũng nói vì mọi người.",
                                      "Hận Minh với bàn tay cầm xà beng nhưng vẫn muốn được gọi là người tốt.",
                                      "Hận những gương mặt im lặng sau cửa, không trực tiếp cướp, nhưng chờ người khác cướp xong để được chia phần.",
                                      "Hận cả chính mình.",
                                      "Vì quá muộn mới hiểu, trong tai họa, lòng tốt không có cửa khóa sẽ biến thành bảng chỉ đường cho kẻ xấu.",
                                      "Có người lục đến ngăn kéo dưới bàn làm việc.",
                                      "\"Ê, nó còn sổ ghi đồ nè.\"",
                                      "Lâm An cố ngẩng đầu.",
                                      "Đừng.",
                                      "Trong cuốn sổ đó có danh sách những thứ cô đã giấu, vị trí mấy chai nước nhỏ trong hộp giày, túi thuốc kháng sinh nhét sau tấm ốp bếp, số pin dự phòng cô bọc nylon thả trong thùng gạo.",
                                      "Đó là chút đường sống cuối cùng của cô.",
                                      "Minh nhặt cuốn sổ lên. Máu trên cánh tay hắn nhỏ xuống bìa giấy.",
                                      "Hắn nhìn cô, ánh mắt lạnh đi.",
                                      "\"Cô giấu kỹ thật.\"",
                                      "Lâm An cười.",
                                      "Lần này cô cười ra tiếng.",
                                      "\"Ừ.\" Cô nói. \"Tiếc là chưa đủ kỹ.\"",
                                      "Mặt Minh sa sầm.",
                                      "Xà beng lại giơ lên.",
                                      "Khoảnh khắc ấy, ngoài cửa sổ chớp sáng. Không phải sét. Là ánh nổ từ trạm điện phía xa, đỏ rực một góc trời mưa. Cả căn phòng rung nhẹ. Tiếng người ngoài hành lang hoảng loạn kêu lên.",
                                      "Lâm An nhìn ánh đỏ phản chiếu trên mặt nước bẩn.",
                                      "Nếu có kiếp sau...",
                                      "Không.",
                                      "Nếu thật sự có kiếp sau, cô sẽ không cầu ai thương.",
                                      "Cô sẽ khóa cửa sớm hơn.",
                                      "Giấu đồ sâu hơn.",
                                      "Học cách nói không trước khi lòng tốt bị người ta cầm dao ép thành nghĩa vụ.",
                                      "Xà beng rơi xuống.",
                                      "Bóng tối nuốt lấy cô.",
                                      "...",
                                      "\"Cô ơi, nhận hàng giúp em.\"",
                                      "Lâm An mở mắt.",
                                      "Ánh sáng trắng từ đèn trần làm cô nhức mắt. Cô nằm trên sofa phòng khách, điều hòa thổi lạnh vào cổ, trên người đắp một cái chăn mỏng màu xám. Không có nước bẩn. Không có mùi cống. Không có tiếng đập cửa.",
                                      "Ngoài cửa vang lên tiếng chuông.",
                                      "Tinh tong.",
                                      "\"Cô An ơi, đơn nước suối của cô tới rồi.\"",
                                      "Lâm An bật dậy quá nhanh, đầu choáng váng. Cô chống tay xuống bàn trà, chạm phải một thứ lạnh và khô.",
                                      "Điện thoại.",
                                      "Màn hình sáng lên.",
                                      "Ngày 17 tháng 7.",
                                      "Mười giờ mười hai phút sáng.",
                                      "Lâm An nhìn chằm chằm vào dòng ngày tháng ấy.",
                                      "Tim cô đập mạnh đến mức đau lồng ngực.",
                                      "Không thể nào.",
                                      "Đây là ba mươi ngày trước trận mưa đầu tiên.",
                                      "Ba mươi ngày trước khi tầng hầm chung cư ngập.",
                                      "Ba mươi ngày trước khi điện mất.",
                                      "Ba mươi ngày trước khi nước sạch trở thành thứ có thể khiến hàng xóm phá cửa nhà nhau.",
                                      "Chuông cửa lại vang lên.",
                                      "Tinh tong.",
                                      "Người giao hàng bên ngoài có vẻ mất kiên nhẫn.",
                                      "\"Cô ơi?\"",
                                      "Lâm An đứng dậy. Chân cô mềm, nhưng sàn nhà dưới chân khô ráo, sạch sẽ, mát lạnh. Cô đi đến cửa, nhìn qua mắt mèo.",
                                      "Một thanh niên mặc áo giao hàng đứng ngoài, bên cạnh là bốn thùng nước suối.",
                                      "Bốn thùng.",
                                      "Quá ít.",
                                      "Kiếp trước, cô đã nghĩ bốn thùng là nhiều.",
                                      "Lâm An mở cửa.",
                                      "Người giao hàng cười nhẹ nhõm.",
                                      "\"Cô kiểm tra giúp em nha. Bốn thùng nước, mỗi thùng hai mươi bốn chai.\"",
                                      "Lâm An nhìn những chai nước trong suốt nằm ngay ngắn trong lớp nylon.",
                                      "Một chai năm trăm mililit.",
                                      "Kiếp trước, nửa chai như vậy đã làm cả tầng mười bảy lộ ra răng nanh.",
                                      "\"Anh chờ tôi một chút.\"",
                                      "Cô cầm điện thoại, mở ứng dụng ngân hàng.",
                                      "Số dư: 47.382.000 đồng.",
                                      "Không nhiều.",
                                      "Nhưng đủ để bắt đầu.",
                                      "\"Anh có nhận đơn riêng không?\" Lâm An hỏi.",
                                      "Người giao hàng ngẩn ra.",
                                      "\"Dạ?\"",
                                      "\"Tôi cần mua thêm nước. Rất nhiều nước. Giao nhiều chuyến, nhiều địa chỉ, tiền công tính riêng.\"",
                                      "Anh ta nhìn cô như nhìn một người vừa mất ngủ.",
                                      "\"Cô mua làm gì nhiều vậy?\"",
                                      "Lâm An cúi xuống, xé lớp nylon của một thùng nước. Đầu ngón tay cô vẫn run, nhưng giọng đã bình tĩnh lại.",
                                      "\"Nhà tôi sắp sửa đường ống.\"",
                                      "Cô ngẩng đầu nhìn người giao hàng.",
                                      "\"Mua trước cho chắc.\"",
                                      "Trong thang máy phía sau, tiếng nói quen thuộc vang lên.",
                                      "\"Ủa An, mua nước nữa hả con?\"",
                                      "Bà Hạnh tầng mười xách túi rau bước ra, tóc búi gọn, mặt mũi hiền lành như chưa từng đứng sau lưng con trai nhìn cô bị đánh chết.",
                                      "Lâm An quay sang.",
                                      "Hai người nhìn nhau.",
                                      "Trong một giây rất ngắn, bàn tay cô vô thức siết chặt chai nước.",
                                      "Bà Hạnh cười.",
                                      "\"Con gái sống một mình cẩn thận vậy cũng tốt. Nhưng mua nhiều quá coi chừng để hư.\"",
                                      "Lâm An cũng cười.",
                                      "\"Dạ.\"",
                                      "Cô kéo thùng nước vào trong nhà, từng thùng một, không nhờ ai phụ.",
                                      "Trước khi đóng cửa, cô nhìn bà Hạnh thêm lần nữa.",
                                      "\"Lần này con sẽ để kỹ hơn.\""
                                  ],
                         "audioUrls":  {

                                       }
                     }
                 ]
});